// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLgdTGDH7G6QBjP6F6L3Jdf2ZExUFEW08',
    appId: '1:798125896123:web:1dc61ae0754512b211149e',
    messagingSenderId: '798125896123',
    projectId: 'athlo-67d5a',
    authDomain: 'athlo-67d5a.firebaseapp.com',
    storageBucket: 'athlo-67d5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjq5RDki_hsFrTrT1wO_GRU6VL6aGYak',
    appId: '1:798125896123:android:519b9e86a28f9cff11149e',
    messagingSenderId: '798125896123',
    projectId: 'athlo-67d5a',
    storageBucket: 'athlo-67d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIJfAzo2_2_jnXLZMf7vd4tASuvL39vM',
    appId: '1:798125896123:ios:31adf2ef505b74fc11149e',
    messagingSenderId: '798125896123',
    projectId: 'athlo-67d5a',
    storageBucket: 'athlo-67d5a.firebasestorage.app',
    iosBundleId: 'com.example.athlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIJfAzo2_2_jnXLZMf7vd4tASuvL39vM',
    appId: '1:798125896123:ios:31adf2ef505b74fc11149e',
    messagingSenderId: '798125896123',
    projectId: 'athlo-67d5a',
    storageBucket: 'athlo-67d5a.firebasestorage.app',
    iosBundleId: 'com.example.athlo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLgdTGDH7G6QBjP6F6L3Jdf2ZExUFEW08',
    appId: '1:798125896123:web:546cf6e323f1ee5311149e',
    messagingSenderId: '798125896123',
    projectId: 'athlo-67d5a',
    authDomain: 'athlo-67d5a.firebaseapp.com',
    storageBucket: 'athlo-67d5a.firebasestorage.app',
  );
}
